import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Provider from "./provider"; 
import { Toaster } from "react-hot-toast";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "user management",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
       
        {/* <Provider> */}
          {children}
          <Toaster position="top-right" reverseOrder={false} />
          {/* </Provider> */}
        
      </body>
    </html>
  );
}
